all:
  children:
    app:
      vars:
        app_name: project-devops-deploy
        app_image_repository: ghcr.io/abdujabbar/project-devops-deploy
        app_image_tag: "{{ image_tag | default('latest') }}"
        app_container_name: project-devops-deploy
        app_root_dir: /opt/project-devops-deploy
        app_data_dir: "{{ app_root_dir }}/data"
        app_logs_dir: "{{ app_root_dir }}/logs"
        app_container_uid: "100"
        app_container_gid: "101"
        app_http_port: 8080
        app_management_port: 9090
        app_restart_policy: unless-stopped
        app_env:
          SPRING_PROFILES_ACTIVE: dev
          MANAGEMENT_SERVER_PORT: "{{ app_management_port }}"
          JAVA_OPTS: "-Djava.io.tmpdir=/data"
        app_secret_env: "{{ vault_app_secret_env | default({}) }}"
        app_registry_username: "{{ vault_registry_username | default('') }}"
        app_registry_password: "{{ vault_registry_password | default('') }}"
      hosts:
        yc-vm:
          ansible_host: 158.160.15.192
          ansible_user: abdu
          ansible_ssh_private_key_file: ~/.ssh/abdu
          ansible_python_interpreter: /usr/bin/python3.12
          app_user: abdu
          firewall_allowed_tcp_ports:
            - "22"
            - "80"
            - "443"
            - "8080"
            - "9090"
