all:
  children:
    app:
      hosts:
        yc-vm:
          ansible_host: 158.160.15.192
          ansible_user: abdu
          ansible_ssh_private_key_file: ~/.ssh/abdu
          ansible_python_interpreter: /usr/bin/python3.12
          app_user: abdu
          firewall_allowed_tcp_ports:
            - "22"
            - "80"
            - "443"
            - "8080"
            - "9090"
